# Generated by Django 5.2.4 on 2025-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
