# Generated by Django 5.2.4 on 2025-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_parkingplace_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='allowed_vehicle_types',
            field=models.TextField(blank=True, help_text='Comma-separated values of allowed vehicle types'),
        ),
    ]
