# Generated by Django 5.2.5 on 2025-08-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_parkingplace_allowed_vehicle_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='image1',
            field=models.ImageField(blank=True, help_text='First parking place image', null=True, upload_to='parking_places/'),
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='image2',
            field=models.ImageField(blank=True, help_text='Second parking place image', null=True, upload_to='parking_places/'),
        ),
    ]
