# Generated by Django 5.2.4 on 2025-08-31 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_parkingplace_image1_parkingplace_image2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='area',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='city',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='parkingplace',
            index=models.Index(fields=['owner', 'created_at'], name='owner_parki_owner_i_396a74_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingplace',
            index=models.Index(fields=['city', 'area'], name='owner_parki_city_91c18a_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['place', 'is_available'], name='owner_parki_place_i_9dc815_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingslot',
            index=models.Index(fields=['is_available'], name='owner_parki_is_avai_4daa1b_idx'),
        ),
    ]
