# Generated by Django 5.2.4 on 2025-08-31 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_booking_vehicle_details'),
        ('owner', '0005_alter_parkingplace_area_alter_parkingplace_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van'), ('suv', 'SUV'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='customer_bo_custome_7ab1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'created_at'], name='customer_bo_custome_3ea010_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['slot', 'status'], name='customer_bo_slot_id_1403d6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time', 'end_time'], name='customer_bo_start_t_222690_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_time'], name='customer_bo_status_ada380_idx'),
        ),
    ]
