# Generated by Django 5.2.5 on 2025-08-31 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_booking_created_at_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('parking_place_name', models.CharField(max_length=120)),
                ('slot_code', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_number_plate', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='customer.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['receipt_number'], name='customer_re_receipt_6955d8_idx'), models.Index(fields=['customer_name'], name='customer_re_custome_7bf6b1_idx'), models.Index(fields=['created_at'], name='customer_re_created_d8d927_idx')],
            },
        ),
    ]
