# Generated by Django 5.2.5 on 2025-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2 Wheeler'), ('3_wheeler', '3 Wheeler'), ('4_wheeler', '4 Wheeler'), ('single_axle', 'Single Axle'), ('double_axle', 'Double Axle'), ('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van'), ('suv', 'SUV'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
